In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

df = pd.read_csv(
    "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day28-column-transformer/covid_toy.csv"
)

df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [19]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [15]:
X_train

    age  gender  fever   cough       city
92   82  Female  102.0  Strong    Kolkata
44   20    Male  102.0  Strong      Delhi
93   27    Male  100.0    Mild    Kolkata
78   11    Male  100.0    Mild  Bangalore
57   49  Female   99.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
28   16    Male  104.0    Mild    Kolkata
50   19    Male  101.0    Mild      Delhi
0    60    Male  103.0    Mild    Kolkata
49   44    Male  104.0    Mild     Mumbai
3    31  Female   98.0    Mild    Kolkata

[80 rows x 5 columns]

1. Aam Zindagi

In [21]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape
(80, 1)

(80, 1)

In [35]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [40]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [45]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values


# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [ ]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

Mentos Zindagi

In [52]:
from sklearn.compose import ColumnTransformer

In [61]:
# transformer = ColumnTransformer(transformers=[
#     ('tnf1',SimpleImputer(),['fever']),
#     ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
#     ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
# ],remainder='passthrough')


transformer = ColumnTransformer(transformers=[
    ('handlingMissingValues',SimpleImputer(),['fever']),
    ('PerformingOrdinalEncoding',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('PerformingOneHotEncoding',OneHotEncoder(), ['gender','city'])
], remainder='passthrough')

transformer.fit_transform(X_train)

array([[ 98.        ,   1.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         12.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         10.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         34.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   1.        ,
         60.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         64.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         20.        ],
       [100.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         13.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         50.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         80.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         27.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         83.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   1.        ,
         14.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         31.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   1.        ,
         65.        ],
       [102.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ,   1.        ,
         74.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         15.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         49.        ],
       [ 99.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         65.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   1.        ,
         81.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         27.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
          8.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         26.        ],
       [100.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         47.        ],
       [100.76712329,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         79.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         40.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         42.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   1.        ,
         19.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   1.        ,
         69.        ],
       [104.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         54.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         51.        ],
       [104.        ,   0.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         25.        ],
       [104.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ,   1.        ,
         42.        ],
       [100.76712329,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         38.        ],
       [100.76712329,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ,   1.        ,
         23.        ],
       [100.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         11.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         83.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         18.        ],
       [102.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
          5.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   1.        ,
         81.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         71.        ],
       [100.76712329,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         42.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         25.        ],
       [102.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         82.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         60.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         69.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         73.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         49.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         68.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
          5.        ],
       [103.        ,   1.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         46.        ],
       [100.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         19.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         34.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         49.        ],
       [100.76712329,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   1.        ,
         20.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         64.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         11.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         83.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         55.        ],
       [104.        ,   0.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         51.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         10.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         48.        ],
       [104.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         56.        ],
       [102.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         33.        ],
       [102.        ,   0.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         64.        ],
       [103.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         70.        ],
       [ 99.        ,   0.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         72.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         19.        ],
       [102.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         24.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         47.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         80.        ],
       [104.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         16.        ],
       [104.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         34.        ],
       [104.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         75.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         27.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         73.        ],
       [ 99.        ,   0.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
         65.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         24.        ],
       [100.76712329,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         82.        ],
       [104.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
         51.        ],
       [100.76712329,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
         75.        ]])