In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

In [4]:
# Load dataset
cancer = load_breast_cancer()

# Create DataFrame with features
df = pd.DataFrame(cancer['data'], columns=cancer['feature_names'])

# Add the target column
df['diagnosis'] = cancer['target']  # 0 = malignant, 1 = benign

df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [5]:
# print(df[['diagnosis']])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
 30  diagnosis                569 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

In [6]:
df.shape

(569, 31)

In [9]:
# Separate features (exclude target)
features = df.drop('diagnosis', axis=1)

# Standardize features
scaler = StandardScaler()
scaled_data = scaler.fit_transform(features)

scaled_data.shape  # should be (569, 30)
# scaled_data

(569, 30)

In [10]:
# applying PCA algorithm

from sklearn.decomposition import PCA

In [21]:
# Reduce to 2 principal components
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(scaled_data)

# Create DataFrame of principal components
principalDf = pd.DataFrame(data=principalComponents, columns=['PC1', 'PC2', 'PC3', 'PC4', 'PC5'])

# Add the target column for visualization
finalDf = pd.concat([principalDf, df[['diagnosis']]], axis=1)
finalDf.head()

        PC1        PC2       PC3       PC4       PC5  diagnosis
0  9.192837   1.948583 -1.123166 -3.633731  1.195110          0
1  2.387802  -3.768172 -0.529293 -1.118264 -0.621775          0
2  5.733896  -1.075174 -0.551748 -0.912083  0.177086          0
3  7.122953  10.275589 -3.232790 -0.152547  2.960878          0
4  3.935302  -1.948072  1.389767 -2.940639 -0.546747          0

In [32]:
principalComponents.shape

(569, 5)

In [29]:
finalDf.shape

(569, 6)

In [22]:
# Eigenvalues → variance along each PC [λ1, λ2]
pca.explained_variance_

array([13.30499079,  5.7013746 ,  2.82291016,  1.98412752,  1.65163324])

In [23]:
pca.explained_variance_ratio_

array([0.44272026, 0.18971182, 0.09393163, 0.06602135, 0.05495768])

In [38]:
pca.components_.shape

(5, 30)

In [37]:
# convarince matrix
pca.get_covariance().shape

(30, 30)